const m = (c, m)=>{ return { code: c, message: m }; };

module.exports = { 
    reg_failed:                                 t => m(0, t('reg_failed')),
    account_same_email_exist:                   t => m(1, t('account_same_email_exist')),
    account_doesnt_exist_active:                t => m(2, t('account_doesnt_exist_active')),
    error_retrive_roles:                        t => m(3, t('error_retrive_roles')),
    wrong_password:                             t => m(4, t('wrong_password')),
    auth_no_token:                              t => m(5, t('auth_no_token')),
    auth_expired:                               t => m(6, t('auth_expired')),
    nsql:                                       t => m(7, t('nsql')),
    record_not_found:                           t => m(8, t('record_not_found')),
    update_record_failed:                       t => m(9, t('update_record_failed')),
    email_invalid:                              t => m(10, t('email_invalid')),
    must_not_be_empty:                          t => m(11, t('must_not_be_empty')),
    password_invalid_rules:                     t => m(12, t('password_invalid_rules')),
    account_same_email_exist:                   t => m(13, t('account_same_email_exist')),
    some_fields_invalid:                        t => m(14, t('some_fields_invalid')),
    wrong_user_pass:                            t => m(15, t('wrong_user_pass')),
    failed_to_create_account_contact_support:   t => m(16, t('failed_to_create_account_contact_support')),
    failed_to_login_contact_support:            t => m(17, t('failed_to_login_contact_support')),
    password_reset_link_invalid:                t => m(18, t('password_reset_link_invalid')),
    password_reset_link_expired:                t => m(19, t('password_reset_link_expired')),
    you_must_verifiy_account_to_login:          t => m(20, t('you_must_verifiy_account_to_login')),
    invalid_verification_url:                   t => m(21, t('invalid_verification_url')),
    failed_to_update_profile:                   t => m(22, t('failed_to_update_profile')),
    failed_to_create_account:                   t => m(23, t('failed_to_create_account')),
    record_deleted:                             t => m(24, t('record_deleted')),
    record_updated:                             t => m(25, t('record_updated')),
    password_reset_success:                     t => m(26, t('password_reset_success')),
    password_reset_link_sent_to_email:          t => m(27, t('password_reset_link_sent_to_email')),
    account_verified_you_can_login:             t => m(28, t('account_verified_you_can_login')),
    registration_success_check_email:           t => m(29, t('registration_success_check_email')),
    old_password_incorrect:                     t => m(30, t('old_password_incorrect')),
    auth_no_permission:                         t => m(31, t('you_dont_have_permission')),
};